# Generated by Django 3.1.5 on 2021-04-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='exclude_from_accounting',
            field=models.BooleanField(default=False),
        ),
    ]
