# Generated by Django 4.1.2 on 2022-10-15 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalPracticePromptInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=1000000, null=True)),
                ('text', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='InformalPracticeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=1000000, null=True)),
                ('instructions', models.CharField(blank=True, max_length=1000000, null=True)),
                ('box_1', models.CharField(max_length=1000000)),
                ('ex_1', models.CharField(default='', max_length=1000000)),
                ('box_2', models.CharField(max_length=1000000)),
                ('ex_2', models.CharField(default='', max_length=1000000)),
                ('box_3', models.CharField(max_length=1000000)),
                ('ex_3', models.CharField(default='', max_length=1000000)),
                ('box_4', models.CharField(max_length=1000000)),
                ('ex_4', models.CharField(default='', max_length=1000000)),
                ('box_5', models.CharField(max_length=1000000)),
                ('ex_5', models.CharField(default='', max_length=1000000)),
                ('box_6', models.CharField(blank=True, default='', max_length=1000000, null=True)),
                ('ex_6', models.CharField(blank=True, default='', max_length=1000000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MBSRUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('has_started', models.BooleanField(default=False)),
                ('is_in_week', models.IntegerField(default=1)),
                ('has_completed', models.BooleanField(default=False)),
                ('day_of_week', models.IntegerField(default=1)),
                ('has_completed_daily_formal_practice', models.BooleanField(default=False)),
                ('has_completed_daily_informal_practice', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InformalPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('situation', models.CharField(max_length=1000)),
                ('feelings_before', models.CharField(max_length=1000)),
                ('feelings_during', models.CharField(max_length=1000)),
                ('learned', models.CharField(max_length=1000)),
                ('feelings_now', models.CharField(max_length=1000)),
                ('week', models.IntegerField(blank=True, default=1)),
                ('day', models.IntegerField(blank=True, default=1)),
                ('mbsr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbsr.mbsruser')),
            ],
        ),
        migrations.CreateModel(
            name='GettingStartedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_of_course_hope', models.CharField(max_length=1000)),
                ('strengths', models.CharField(max_length=1000)),
                ('practice_time', models.CharField(max_length=1000)),
                ('practice_location', models.CharField(max_length=1000)),
                ('prep_time', models.CharField(max_length=1000)),
                ('mbsr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbsr.mbsruser')),
            ],
        ),
        migrations.CreateModel(
            name='FormalPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=10000)),
                ('week', models.IntegerField(blank=True, default=1)),
                ('day', models.IntegerField(blank=True, default=1)),
                ('mbsr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbsr.mbsruser')),
            ],
        ),
    ]
