# Generated by Django 3.1.5 on 2021-04-30 17:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('account_type', models.CharField(choices=[('credit_card', 'credit_card'), ('bank_account', 'bank_account'), ('other', 'other')], default='other', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_from_account', models.BooleanField(default=False)),
                ('paid_to', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('has_expense_items', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_from_account', to='budgeter.accountbase')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ledger_type', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=10)),
                ('transaction_type', models.CharField(choices=[('E', 'expense'), ('C', 'creditcardpayment'), ('D', 'deposit'), ('W', 'withdrawal'), ('T', 'transfer'), ('A', 'adjustment'), ('O', 'other')], default='other', max_length=20)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeter.accountbase')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeter.description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('transaction_record', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeter.transactionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TransferAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_from_transaction_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trf_account_from', to='budgeter.transactionrecord')),
                ('transfer_to_transaction_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trf_account_to', to='budgeter.transactionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItemSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('expense', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budgeter.expense')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeter.subcategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction_record',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_expense', to='budgeter.transactionrecord'),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('transaction_record', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeter.transactionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_transaction_record', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccp_bank_account', to='budgeter.transactionrecord')),
                ('credit_card_transaction_record', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccp_credit_card', to='budgeter.transactionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('account_base', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeter.accountbase')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('cash', 'Cash')], max_length=30)),
                ('exclude_from_available_funds', models.BooleanField(default=False)),
                ('account_base', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeter.accountbase')),
            ],
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('transaction_record', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeter.transactionrecord')),
            ],
        ),
    ]
