# Generated by Django 4.1.2 on 2022-10-20 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_backend', '0002_alter_item_category_alter_item_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('P', 'Posters'), ('C', 'Clothing'), ('T', 'Tip'), ('M', 'Mugs')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('D', 'danger'), ('S', 'seconary')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_backend.item'),
        ),
    ]
