# Generated by Django 4.1.2 on 2022-10-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_backend', '0007_alter_address_address_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('T', 'Tip'), ('P', 'Posters'), ('M', 'Mugs'), ('C', 'Clothing')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('S', 'seconary'), ('D', 'danger'), ('P', 'primary')], max_length=1, null=True),
        ),
    ]
