# Generated by Django 4.1.2 on 2022-10-26 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_backend', '0011_remove_order_ref_code_alter_item_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session_id',
        ),
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('C', 'Clothing'), ('T', 'Tip'), ('M', 'Mugs'), ('P', 'Posters')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('S', 'seconary'), ('D', 'danger'), ('P', 'primary')], max_length=1, null=True),
        ),
    ]
