# Generated by Django 4.1.2 on 2022-10-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_backend', '0012_alter_item_category_alter_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('S', 'shipping'), ('B', 'billing')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('M', 'Mugs'), ('C', 'Clothing'), ('T', 'Tip'), ('P', 'Posters')], max_length=2, null=True),
        ),
    ]
