# Generated by Django 4.1.2 on 2022-10-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_backend', '0017_alter_address_address_type_alter_address_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('S', 'seconary'), ('D', 'danger'), ('P', 'primary')], max_length=1, null=True),
        ),
    ]
